apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed-svc
  namespace: default
  selfLink: /api/v1/namespaces/default/services/backend-feed-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-feed
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: udagram-backend-feed
